config/routes.rb
FROfficeSports::Application.routes.draw do

  root :to => 'players#index'

  resources :players do
    get :sort_active
    get :sort_inactive
  end
  resources :games do
    put :delete_last_game
  end
  resources :tt_games
  resources :tt_players
  resources :seasons

  get "games/random_game"

end

app/models/tt_player.rb
class TtPlayer < ActiveRecord::Base
end

app/controllers/tt_players_controller.rb
class TtPlayersController < ApplicationController
end

app/helpers/tt_players_helper.rb
module TtPlayersHelper
end

app/views/tt_players/index.html.haml
%header
	%span.logo= image_tag("FRlogo.png", alt: "Front Rush")
	%span.foosball=image_tag("Foosball.png", :size => "48x36")
	%span.foosball_text Foosball
	%span.TT=link_to image_tag("TT.png", :size => "48x36"), "#"
	%span.TT_text Table Tennis (Coming Soon!)
%body
	#container_left
		%h1.players
			%p.player_text Player Rankings
		%ul.players_container
			%li.player_row.header
				%span.rank.header Rank
				%span.name.header Name
				%span.games_played.header GP
				%span.ones_record.header 1v1 Record
				%span.twos_record.header 2v2 Record
				%span.on_offense.header On Offense
				%span.on_defense.header On Defense
				%span.points_for.header PF
				%span.points_against.header PA
				%span.points_diff.header +/-
				%span.ELO.header Rating
			-TtPlayer.order("position ASC").each do |p|
				-$ones_wins = p.wins - p.wins_on_offense - p.wins_on_defense
				-$ones_losses = p.losses - p.losses_on_offense - p.losses_on_defense
				%li.player_row{:id => p.id}
					%span.rank=p.position
					%span.name=p.name
					%span.games_played="#{p.wins + p.losses}"
					%span.ones_record="#{$ones_wins} - #{$ones_losses}"
					%span.twos_record="#{p.wins - $ones_wins} - #{p.losses - $ones_losses}"
					%span.on_offense="#{p.wins_on_offense} - #{p.losses_on_offense}"
					%span.on_defense="#{p.wins_on_defense} - #{p.losses_on_defense}"
					-$points_diff = p.points_for - p.points_against
					%span.points_for="#{p.points_for}"
					%span.points_against="#{p.points_against}"
					-if $points_diff > 0
						%span.points_diff.green="+#{$points_diff}"
					-elsif $points_diff < 0
						%span.points_diff.red="#{$points_diff}"
					-else
						%span.points_diff="#{$points_diff}"
					%span.ELO=number_with_precision(p.elo_rating, :precision => 2)
			%li.player_row.bottom		
				%p.add_new_stuff
					%span.add_player=button_to "Add Player", new_player_path, :method => "get", :class => "standard_button"
					%span.add_new_game=button_to "Enter Game", new_game_path, :method => "get", :class => "standard_button"
					%span.random=button_to "Random Game", games_random_game_path, :method => "get", :class => "standard_button"
				%p.last_game
					-$last_game = Game.last
					-unless $last_game == nil
						%span.text="*The previous game between #{$last_game.blue_offense}/#{$last_game.blue_defense} and #{$last_game.red_offense}/#{$last_game.red_defense} had an ELO swing of #{number_with_precision($last_game.elo_swing, :precision => 4)}."
			%li.footer

app/views/tt_players/new.html.haml
%h1 Create a new player!
= form_for(@tt_player) do |f|
  = f.hidden_field :wins, :value => 0
  = f.hidden_field :losses, :value => 0
  = f.hidden_field :wins_on_offense, :value => 0
  = f.hidden_field :losses_on_offense, :value => 0
  = f.hidden_field :wins_on_defense, :value => 0
  = f.hidden_field :losses_on_defense, :value => 0
  = f.hidden_field :elo_rating, :value => 1500
  = f.hidden_field :points_for, :value => 0
  = f.hidden_field :points_against, :value => 0
  = f.hidden_field :position, :value => 1

  .field
    = f.label "Name"
    %br/
    = f.text_field :name
  .actions
    = f.submit