config/routes.rb
FROfficeSports::Application.routes.draw do

  root :to => 'players#index'

  resources :players do
    get :sort_active
    get :sort_inactive
  end
  resources :games do
    put :delete_last_game
  end
  resources :tt_games
  resources :tt_players
  resources :seasons

  get "games/random_game"

end

app/models/player.rb
class Player < ActiveRecord::Base
	validates_presence_of :name
	attr_accessible :remember_token, :name, :wins, :losses, :wins_on_offense, :losses_on_offense, :active
	attr_accessible :wins_on_defense, :losses_on_defense, :elo_rating, :points_for, :points_against, :overall_elo
	attr_accessible :win_streak, :loss_streak, :shutout_for, :shutout_against, :current_streak
	has_many :games
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_action :sort_by_elo
	helper_method :sort_column, :sort_direction

	def show

	end

	def index
		@season = Season.new
		@game = Game.new
		@player = Player.new
	end

	def new
		@player = Player.new
	end

	def create
		@player = Player.new(params[:player])
		@player.save
		redirect_to players_path
	end

	def update
		@player = Player.find(params[:id])
		@player.update(params[:player])
		redirect_to players_path
	end

	def new_game
		respond_to do |format|
			format.js
		end
	end

	def sort_active
		session[:active_var] = 1
		redirect_to players_path
	end

	def sort_inactive
		session[:active_var] = 0
		redirect_to players_path
	end

	def sort_by_elo

		#Set player tab
		if session[:active_var] == nil
			session[:active_var] = 1
		end
		@player_list = Player.where(:active => session[:active_var]).order("overall_elo DESC")

		#Set current season
		@current_season = Season.where(:active => 1).first
		if @current_season == nil
			@current_season = Season.create(:name => "Summer 2014", :active => 1)
		end

		#Set 'last game' variables
		$last_game = Game.last
		if $last_game != nil
			$last_game_red_o = Player.find($last_game.red_offense)
			$last_game_red_d = Player.find($last_game.red_defense)
			$last_game_blue_o = Player.find($last_game.blue_offense)
			$last_game_blue_d = Player.find($last_game.blue_defense)
		end

		# $rank = 1
		# if Player.first != nil
		# 	$previous_rank = Player.order("elo_rating DESC").first.elo_rating
		# end

		# Player.order("elo_rating DESC").each do |p|
		# 	if p.elo_rating == $previous_rank
		# 		p.position = $rank
		# 	else
		# 		$rank += 1
		# 		p.position = $rank
		# 	end
		# 	$previous_rank = p.elo_rating
		# 	p.save
		# end
	end
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/index.html.haml
%header
	%span.logo= image_tag("FRlogo.png", alt: "Front Rush")
	%span.foosball=image_tag("Foosball.png", :size => "48x36")
	%span.foosball_text Foosball
	%span.TT=link_to image_tag("TT.png", :size => "48x36"), "#"
	%span.TT_text Table Tennis (Coming Soon!)
%body
	-$rank = 1
	.modal
	#centered_form.new_game
		%h1 Create a new Game!
		=form_for(@game) do |f|
			.field
				= f.label "Winning Score: "
				= f.number_field :winning_score
				%br/
				= f.label "Losing Score: "
				= f.number_field :losing_score
				%br/
				= f.label "Blue Offensive Player: "
				= f.select(:blue_offense, Player.all.where(:active => 1).order(:name).collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'})
				%br/
				= f.label "Blue Defensive Player: "
				= f.select(:blue_defense, Player.all.where(:active => 1).order(:name).collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'})
				%br/
				= f.label "Red Offensive Player: "
				= f.select(:red_offense, Player.all.where(:active => 1).order(:name).collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'})
				%br/
				= f.label "Red Defensive Player: "
				= f.select(:red_defense, Player.all.where(:active => 1).order(:name).collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'})
				%br/
				=f.label "Winner? "
				= f.select :winner, ["Blue Team", "Red Team"]
				%br/
			%br/
			.actions
				= f.submit
	#centered_form.new_player
		%h1 Create a new player!
		= form_for(@player) do |f|
			= f.hidden_field :wins, :value => 0
			= f.hidden_field :losses, :value => 0
			= f.hidden_field :wins_on_offense, :value => 0
			= f.hidden_field :losses_on_offense, :value => 0
			= f.hidden_field :wins_on_defense, :value => 0
			= f.hidden_field :losses_on_defense, :value => 0
			= f.hidden_field :elo_rating, :value => 1500
			= f.hidden_field :overall_elo, :value => 1500
			= f.hidden_field :active, :value => 1
			= f.hidden_field :points_for, :value => 0
			= f.hidden_field :points_against, :value => 0
			= f.hidden_field :position, :value => 1
			= f.hidden_field :win_streak, :value => 0
			= f.hidden_field :loss_streak, :value => 0
			= f.hidden_field :shutout_for, :value => 0
			= f.hidden_field :shutout_against, :value => 0
			= f.hidden_field :current_streak, :value => 0

			.field
				= f.label "Name"
				= f.text_field :name
			%br/
			.actions
				= f.submit
	#centered_form.random_game
		%h1 Type in 4 players and a random matchup will be displayed
		%br/
		%form{:autocomplete => "on", :onsubmit => "randomPlayer()"}
			Player 1:
			%input#player1{:type => "text"}/
			%br/
			Player 2:
			%input#player2{:type => "text"}/
			%br/
			Player 3:
			%input#player3{:type => "text"}/
			%br/
			Player 4:
			%input#player4{:type => "text"}/
			%br/
			/ Player 5: <input type="text" id= "player5"><br>
			/ Player 6: <input type="text" id= "player6"><br>
			%br/
			%br/
			%input#assignTeam{:type => "checkbox", :value => "Yes"}/
			Check to also Assign Offense & Defense
			%br/
			%br/
			%br/
			%input{:onclick => "randomPlayer()", :type => "button", :value => "Roll the dice!"}/
		%br/
		%p
			Red Team:
			%span#redTeam
			%span#rankinG1
		%p
			Blue Team:
			%span#blueTeam
			%span#rankinG222
	#centered_form.season
		%h1 Start a new season
		%br/
		=form_for(@season) do |s|
			.field
				= s.label "Season name: "
				= s.text_field :name
				%br/
				.actions
					=s.submit
	-Player.all.each do |p|
		#centered_form.statistics{:player_id => p.id}
			.close="X"
			%h1.center="#{p.name}'s Stats"
			=link_to "Edit player", "#", :remote => true, :method => "get", :class => "edit-player-link", :player_id => "#{p.id}", :style => "margin-bottom: 25px; display: block;"
			%table.misc_stats
				%tr
					%td="Biggest Win Streak"
					-if p.win_streak == 0
						%td="0"
					-else
						%td.green="+#{p.win_streak}"
				%tr
					%td="Biggest Loss Streak"
					-if p.loss_streak == 0
						%td="0"
					-else
						%td.red="#{p.loss_streak}"
				%tr
					%td="Shut Outs For"
					%td="#{p.shutout_for}"
				%tr
					%td="Shut Outs Against"
					%td="#{p.shutout_against}"
			%h2="Statistics"
			%table.misc_stats
				%tr
					%td="PF %"
					-if p.points_for + p.points_against == 0
						%td="-"
					-else
						-percentage = number_with_precision(p.points_for.to_f / (p.points_for.to_f + p.points_against.to_f) * 100, :precision => 2)
						%td="#{percentage}%"
				%tr
					%td="On Offense"
					-if p.wins_on_offense + p.losses_on_offense == 0
						%td="-"
					-else
						-percentage = number_with_precision(p.wins_on_offense.to_f / (p.wins_on_offense + p.losses_on_offense).to_f*100, :precision => 2)
						%td="#{percentage}%"
				%tr
					%td="On Defense"
					-if p.wins_on_defense + p.losses_on_defense == 0
						%td="-"
					-else
						-percentage = number_with_precision(p.wins_on_defense.to_f / (p.wins_on_defense + p.losses_on_defense).to_f*100, :precision => 2)
						%td="#{percentage}%"
				%tr
					%td="Overall"
					-if p.wins_on_offense + p.losses_on_offense + p.wins_on_defense + p.losses_on_defense == 0
						%td="-"
					-else
						-percentage = number_with_precision((p.wins_on_offense + p.wins_on_defense).to_f / (p.wins_on_offense + p.losses_on_offense + p.wins_on_defense + p.losses_on_defense).to_f*100, :precision => 2)
						%td="#{percentage}%"
			%table
				%tr.elo.header
					%td.season.header="Season"
					%td.elo.header="ELO"
				-Season.all.order("id ASC").each do |s|
					-$se = SeasonalELO.where(:player_id => p.id, :season => s.id).first
					%tr.elo{:season_id => s.id}
						%td.season="#{s.name}"
						-if $se != nil
							%td.elo=number_with_precision($se.elo, :precision => 2)
						-else
							%td.elo="--NO DATA--"
		#centered_form.edit-player{:class => "edit-#{p.id}"}
			%h1.center="Edit Player"
			-@player = Player.find(p.id)
			=form_for(@player) do |pl|
				.field
					= pl.label "Name: "
					= pl.text_field :name
					%br/
					= pl.label "Active: "
					= pl.check_box :active
					.actions
						=pl.submit
	#container_left
		%h1.center="Player Rankings"
		#tabs
			-if session[:active_var] == 1
				=link_to "Active", player_sort_active_path(0), :class => "selected", :id => "active"
				=link_to "Inactive", player_sort_inactive_path(0), :id => "inactive"
			-else
				=link_to "Active", player_sort_active_path(0), :id => "active"
				=link_to "Inactive", player_sort_inactive_path(0), :class => "selected", :id => "inactive"
		%div.players_container
			%table
				%tr.player_row.header
					%td.rank.header Rank
					%td.name.header Name
					%td.games_played.header GP
					%td.twos_record.header Record
					%td.on_offense.header On Offense
					%td.on_defense.header On Defense
					%td.points_for.header PF
					%td.points_against.header PA
					%td.current_streak.header Current Streak
					%td.points_diff.header +/-
					%td.ELO.season.header #{@current_season.name}
					%td.ELO.header Overall
				-@player_list.each do |p|
					-$ones_wins = p.wins - p.wins_on_offense - p.wins_on_defense
					-$ones_losses = p.losses - p.losses_on_offense - p.losses_on_defense
					%tr.player_row{:id => p.id}
						%td.rank=$rank
						-$rank = $rank + 1
						-$shutout_for_rating = 0
						-$shutout_against_rating = 0
						-$total = p.wins + p.losses
						-imgAry=[]
						-if($total > 0)
							-if(p.shutout_for > 0)
								-$shutout_for_rating = p.shutout_for.to_f/$total
							-if(p.shutout_against > 0)
								-$shutout_against_rating = p.shutout_against.to_f/$total
						-if $total == 0
							%td.name=image_tag('baby.gif', :size => "20x20", :alt => "novice") + "  " + p.name
						-else
							-if $shutout_for_rating > 0.03
								-imgAry.push(image_tag('crown.gif', :size => "20x20", :alt => "master"))
							-elsif p.shutout_for > 0
								-imgAry.push(image_tag('sword.png', :size => "20x20", :alt => "master"))
							-if $shutout_against_rating > 0.0005
								-imgAry.push(image_tag('skull.png', :size => "20x20", :alt => "scrub"))
							-if imgAry.length == 0
								%td.name=p.name
							-if imgAry.length == 1
								%td.name
									=imgAry.at(0)
									=p.name
							-elsif imgAry.length >= 2
								%td.name
									=imgAry.at(0)
									=imgAry.at(1)
									=p.name
						%td.games_played="#{p.wins + p.losses}"
						%td.twos_record="#{p.wins - $ones_wins} - #{p.losses - $ones_losses}"
						%td.on_offense="#{p.wins_on_offense} - #{p.losses_on_offense}"
						%td.on_defense="#{p.wins_on_defense} - #{p.losses_on_defense}"
						-$points_diff = p.points_for - p.points_against
						%td.points_for="#{p.points_for}"
						%td.points_against="#{p.points_against}"
						-if p.current_streak > 0
							%td.points_diff.green="+#{p.current_streak}"
						-elsif p.current_streak < 0
							%td.points_diff.red="#{p.current_streak}"
						-else
							%td.points_diff="#{p.current_streak}"
						-if $points_diff > 0
							%td.points_diff.green="+#{$points_diff}"
						-elsif $points_diff < 0
							%td.points_diff.red="#{$points_diff}"
						-else
							%td.points_diff="#{$points_diff}"
						-if SeasonalELO.where(:season => @current_season.id, :player_id => p.id).first != nil
							%td.season_elo=number_with_precision(SeasonalELO.where(:season => @current_season.id, :player_id => p.id).first.elo, :precision => 2)
						-else
							%td.season_elo=1500.00
						%td.ELO=number_with_precision(p.overall_elo, :precision => 2)
		%div.player_row.bottom
			%p.add_new_stuff
				%span.add_player=button_to "Add Player", "#", :remote => true, :method => "get", :class => "standard_button", :id => "new_player_button"
				%span.add_new_game=button_to "Enter Game", "#", :remote => true, :method => "get", :class => "standard_button", :id => "new_game_button"
				%span.random=button_to "Random Game", "#", :remote => true, :method => "get", :class => "standard_button", :id => "random_game_button"
				%span.season=button_to "Start New Season", "#", :remote => true, :method => "get", :class => "standard_button", :id=> "new_season_button"
			%p.last_game
				-unless $last_game == nil
					-if $last_game.winner == "Red Team" and $last_game_red_o != $last_game_red_d
						%span.text="*#{$last_game_red_o.name} and #{$last_game_red_d.name}'s #{$last_game.winning_score} - #{$last_game.losing_score} victory over #{$last_game_blue_o.name} and #{$last_game_blue_d.name} had an ELO swing of #{number_with_precision($last_game.elo_swing, :precision => 4)}."
					-elsif $last_game.winner == "Blue Team" and $last_game_blue_o != $last_game_blue_d
						%span.text="*#{$last_game_blue_o.name} and #{$last_game_blue_d.name}'s #{$last_game.winning_score} - #{$last_game.losing_score} victory over #{$last_game_red_o.name} and #{$last_game_red_d.name} had an ELO swing of #{number_with_precision($last_game.elo_swing, :precision => 4)}."
					-elsif $last_game.winner == "Red Team" and $last_game_red_o == $last_game_red_d
						%span.text="*#{$last_game_red_o.name}'s #{$last_game.winning_score} - #{$last_game.losing_score} victory over #{$last_game_blue_o.name} in 1v1 had an ELO swing of #{number_with_precision($last_game.elo_swing, :precision => 4)}."
					-else
						%span.text="*#{$last_game_blue_o.name}'s #{$last_game.winning_score} - #{$last_game.losing_score} victory over #{$last_game_red_o.name} in 1v1 had an ELO swing of #{number_with_precision($last_game.elo_swing, :precision => 4)}."
					%span.text=link_to "Delete this game", game_delete_last_game_path($last_game.id), :method => "put", :confirm => "Are you sure you want to do that?"
			%br/

app/views/players/new.html.haml
%h1 Create a new player!
= form_for(@player) do |f|
  = f.hidden_field :wins, :value => 0
  = f.hidden_field :losses, :value => 0
  = f.hidden_field :wins_on_offense, :value => 0
  = f.hidden_field :losses_on_offense, :value => 0
  = f.hidden_field :wins_on_defense, :value => 0
  = f.hidden_field :losses_on_defense, :value => 0
  = f.hidden_field :elo_rating, :value => 1500
  = f.hidden_field :points_for, :value => 0
  = f.hidden_field :points_against, :value => 0
  = f.hidden_field :position, :value => 1

  .field
    = f.label "Name"
    %br/
    = f.text_field :name
  .actions
    = f.submit